services:
  # PHP Service
  php:
    build: ./php
    container_name: php_app
    volumes:
      - ./symfony:/var/www/html
    networks:
      - app-network

  # PostgreSQL Service
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge